### ISSUE TITLE
More options.

### ISSUE THREAD

**Issue by lebarondemerde** [kylecook80/polybar-port#3]
Hi.

Those should/may also be optional ([HERE](https://github.com/jaagr/polybar/wiki/Compiling)):

libxcb-xrm.so:x11/xcb-util-xrm
libxcb-cursor.so:x11/xcb-util-cursor

Btw, the options descriptions are missing. ^^

You can look how to write them at: /usr/ports/Mk/bsd.options.desc.mk

Ps. python:2 is deprecated you should set python:2.7 instead.

Ps_2. **CATEGORIES= x11** and **OPTIONS_DEFAULT= CURL** seem to have a normal space. They must be a TAB one.

Thanks!

**Comment by lebarondemerde** [comment]
Ah, you do not need to add an option description if there is one in Mk/bsd.options.desc.mk already for that specific option.

**Comment by kylecook80** [comment]
@lebarondemerde So the main problem with python:2.7, is that the CMAKE file for xpp (a git submodule in polybar) uses the version to create the path to the site-packages. So, whenever I use python:2.7, it is unable to find 'xcbgen' as the python executable that xpp is looking for is 'python2' instead of 'python2.7'.

The only way I know to fix this is by creating a separate port for xpp, which I am not quite ready to do. Once that happens, I'll move this to python:2.7 instead of python:2

I honestly don't feel like libxcb-xrm and libxcb-cursor should be optional, as that seems to be a core feature of using polybar with X11.

Hopefully all of the spacing issues are fixed :)
